# Kong Gateway Configuration for Loyalty System Development
_format_version: "3.0"

services:
  - name: user-service
    url: http://user-service:8080
    tags:
      - loyalty
      - microservice
    routes:
      - name: user-service-route
        paths:
          - /api/v1/users
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        strip_path: false

  - name: point-service
    url: http://point-service:8081
    tags:
      - loyalty
      - microservice
    routes:
      - name: point-service-route
        paths:
          - /api/v1/points
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        strip_path: false

  - name: rewards-service
    url: http://rewards-service:8082
    tags:
      - loyalty
      - microservice
    routes:
      - name: rewards-service-route
        paths:
          - /api/v1/rewards
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        strip_path: false

  - name: admin-service
    url: http://admin-service:8083
    tags:
      - loyalty
      - microservice
      - admin
    routes:
      - name: admin-service-route
        paths:
          - /api/v1/admin
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        strip_path: false

  # Health check endpoints aggregation
  - name: health-check
    url: http://user-service:8080
    tags:
      - health
    routes:
      - name: health-route
        paths:
          - /health
        methods:
          - GET
        strip_path: false

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-Auth-Token
        - Authorization
      exposed_headers:
        - X-Auth-Token
        - Authorization
      credentials: true
      max_age: 3600

  - name: rate-limiting
    config:
      minute: 100
      hour: 1000
      policy: local

  - name: request-id
    config:
      header_name: X-Request-ID
      generator: uuid

# Global rate limiting for development
# Production will have more specific rules per service