# Pull Request Validation Workflow
# Validates pull requests with fast feedback
name: PR Validation

on:
  pull_request:
    branches: [ main, develop ]
    types: [opened, synchronize, reopened]

env:
  JAVA_VERSION: '17'

jobs:
  # Fast validation for PR feedback
  pr-validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user-service, point-service, rewards-service, admin-service]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven

      - name: Compile and validate
        run: |
          cd services/${{ matrix.service }}
          mvn clean compile -DskipTests

      - name: Run unit tests only
        run: |
          cd services/${{ matrix.service }}
          mvn test -Dspring.profiles.active=test

      - name: Check code formatting
        run: |
          cd services/${{ matrix.service }}
          mvn spotless:check || true

  # Dependency vulnerability scan for PRs
  pr-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven

      - name: Run dependency vulnerability scan
        run: |
          # Scan each service for vulnerabilities
          for service in user-service point-service rewards-service admin-service; do
            echo "Scanning $service..."
            cd services/$service
            mvn org.owasp:dependency-check-maven:check -DfailBuildOnCVSS=7
            cd ../..
          done